/* ────────────────────────────────────────
   Report Exporter — Generate downloadable
   Markdown report from diagnosis results
   ──────────────────────────────────────── */

import { DiagnosisResponse, DiagnosisIssue } from "./types";

function severityEmoji(s: string): string {
  switch (s) {
    case "CRITICAL": return "🔴";
    case "HIGH": return "🟠";
    case "MEDIUM": return "🟡";
    case "LOW": return "⚪";
    default: return "⚪";
  }
}

function gradeFromScore(score: number): string {
  if (score >= 90) return "A+";
  if (score >= 80) return "A";
  if (score >= 70) return "B";
  if (score >= 60) return "C";
  if (score >= 40) return "D";
  return "F";
}

function formatIssue(issue: DiagnosisIssue, idx: number): string {
  const lines: string[] = [];
  const loc = issue.location?.line_start
    ? ` (Line ${issue.location.line_start}${issue.location.line_end && issue.location.line_end !== issue.location.line_start ? `–${issue.location.line_end}` : ""})`
    : "";

  lines.push(`### ${idx + 1}. ${severityEmoji(issue.severity)} [${issue.severity}] ${issue.title}${loc}`);
  lines.push("");
  lines.push(`**Category:** ${issue.type.replace(/_/g, " ")}  `);
  lines.push(`**Health Impact:** ${issue.health_impact > 0 ? "-" : ""}${Math.abs(issue.health_impact)} points`);
  lines.push("");
  lines.push("**Why This Matters:**");
  lines.push(issue.explanation);
  lines.push("");

  if (issue.location?.code_snippet) {
    lines.push("**Problem Code:**");
    lines.push("```python");
    lines.push(issue.location.code_snippet);
    lines.push("```");
    lines.push("");
  }

  if (issue.suggested_fix) {
    lines.push("**Fix:**");
    lines.push("```python");
    lines.push(issue.suggested_fix);
    lines.push("```");
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  return lines.join("\n");
}

export function generateMarkdownReport(report: DiagnosisResponse): string {
  const now = new Date().toLocaleString();
  const grade = gradeFromScore(report.health_score);
  const critical = report.issues.filter(i => i.severity === "CRITICAL").length;
  const high = report.issues.filter(i => i.severity === "HIGH").length;
  const medium = report.issues.filter(i => i.severity === "MEDIUM").length;
  const low = report.issues.filter(i => i.severity === "LOW").length;

  const lines: string[] = [];

  // Header
  lines.push("# 🩺 ModelDoctor — Diagnosis Report");
  lines.push("");
  lines.push(`> Generated on ${now} by [ModelDoctor](https://modeldoctor.dev) — The MRI for your ML Pipeline`);
  lines.push("");

  // Score card
  lines.push("## Health Score");
  lines.push("");
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| **Score** | **${report.health_score}/100** |`);
  lines.push(`| **Grade** | **${grade}** |`);
  lines.push(`| **Issues Found** | ${report.issues.length} |`);
  lines.push(`| **Diagnosis Time** | ${(report.diagnosis_time_ms / 1000).toFixed(1)}s |`);
  lines.push(`| **AI Model** | ${report.model_used} |`);
  lines.push("");

  // Severity breakdown
  lines.push("### Issue Breakdown");
  lines.push("");
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|-------|`);
  if (critical > 0) lines.push(`| 🔴 Critical | ${critical} |`);
  if (high > 0) lines.push(`| 🟠 High | ${high} |`);
  if (medium > 0) lines.push(`| 🟡 Medium | ${medium} |`);
  if (low > 0) lines.push(`| ⚪ Low | ${low} |`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(report.summary);
  lines.push("");

  // Issues
  if (report.issues.length > 0) {
    lines.push("## Detected Issues");
    lines.push("");
    report.issues.forEach((issue, idx) => {
      lines.push(formatIssue(issue, idx));
    });
  } else {
    lines.push("## ✅ No Issues Detected");
    lines.push("");
    lines.push("Your ML pipeline follows good practices. No silent failures detected.");
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push("*Report generated by ModelDoctor — Team ASTROID (Prabhas N & Poornima Bhat)*  ");
  lines.push("*Open Innovation Track — \"Trustworthy ML, from the start.\"*");

  return lines.join("\n");
}

export function downloadReport(report: DiagnosisResponse) {
  const markdown = generateMarkdownReport(report);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const timestamp = new Date().toISOString().slice(0, 10);

  const a = document.createElement("a");
  a.href = url;
  a.download = `modeldoctor-report-${timestamp}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
